# Generated by Django 3.0 on 2020-04-20 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('slug', models.SlugField(max_length=64, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'theme',
                'verbose_name_plural': 'Themes',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('title', models.CharField(max_length=254, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lang', models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], max_length=2, verbose_name='Language')),
                ('status', models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], verbose_name='Status')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Theme')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
