# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170417_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=30)),
                ('text', models.TextField(verbose_name='Text')),
                ('lang', models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], max_length=2, verbose_name='Language')),
                ('visible', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='page_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Page views'),
        ),
    ]
