# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170419_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('lang', models.CharField(max_length=2, verbose_name='Language')),
                ('activated', models.BooleanField(default=False, verbose_name='Activated')),
                ('activation_code', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Activation code')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
    ]
