# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_emailsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternateURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], max_length=2, verbose_name='Language')),
                ('url', models.URLField(max_length=254, verbose_name='URL')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'alternate URL',
                'verbose_name_plural': 'Alternate URLs',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=254, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='alternateurl',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
