# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170501_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternateurl',
            name='url',
        ),
        migrations.AddField(
            model_name='alternateurl',
            name='alternate_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alternate_post', to='blog.Post', verbose_name='Alternate post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alternateurl',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='Original post'),
        ),
    ]
